// ─────────────────────────────────────────────────────────────────────────────
// SAMPLE CODE — NOT INTENDED FOR PRODUCTION USE.
// This code is provided as a reference implementation only.
// ─────────────────────────────────────────────────────────────────────────────

// ── Auth config — loaded at runtime from config.json (generated by CDK) ──
let CONFIG = null;

async function loadConfig() {
  if (CONFIG) return CONFIG;
  const resp = await fetch('/config.json');
  if (!resp.ok) throw new Error('Failed to load config.json');
  CONFIG = await resp.json();
  CONFIG.redirectUri = window.location.origin;
  // Strip trailing slash from Cognito domain to avoid double-slash in OAuth URLs
  if (CONFIG.cognitoDomain && CONFIG.cognitoDomain.endsWith('/')) {
    CONFIG.cognitoDomain = CONFIG.cognitoDomain.slice(0, -1);
  }
  return CONFIG;
}

// ── Token exchange ──
async function exchangeCodeForTokens(code) {
  const cfg = await loadConfig();
  const body = new URLSearchParams({
    grant_type: 'authorization_code',
    client_id: cfg.clientId,
    redirect_uri: cfg.redirectUri,
    code: code,
  });
  const resp = await fetch(`${cfg.cognitoDomain}/oauth2/token`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: body.toString(),
  });
  if (!resp.ok) throw new Error('Token exchange failed');
  return resp.json();
}

// ── JWT helpers ──
function decodeJwt(token) {
  const payload = token.split('.')[1];
  return JSON.parse(atob(payload.replace(/-/g, '+').replace(/_/g, '/')));
}

function getAccessToken() { return getCookie('awana-session'); }
function getIdToken()     { return getCookie('awana-id-token'); }

// ── Cookie helpers ──
function setCookie(name, value, maxAgeSec) {
  document.cookie = `${name}=${value}; path=/; max-age=${maxAgeSec}; Secure; SameSite=Lax`;
}
function getCookie(name) {
  const cookies = document.cookie.split(';');
  for (const cookie of cookies) {
    const [key, ...rest] = cookie.split('=');
    if (key.trim() === name) return rest.join('=');
  }
  return null;
}
function deleteCookie(name) {
  document.cookie = `${name}=; path=/; max-age=0; Secure; SameSite=Lax`;
}

// ── Logout ──
async function logout() {
  const cfg = await loadConfig();
  deleteCookie('awana-session');
  deleteCookie('awana-id-token');
  const logoutUrl = `${cfg.cognitoDomain}/logout?client_id=${cfg.clientId}&logout_uri=${encodeURIComponent(cfg.redirectUri)}`;
  window.location.href = logoutUrl;
}

// ── Auth init — runs on page load, exposes a promise other scripts can await ──
var authReady = (async function authInit() {
  const cfg = await loadConfig();
  const params = new URLSearchParams(window.location.search);
  const code = params.get('code');

  if (code) {
    // Clear the code from the URL immediately so a refresh won't replay it
    window.history.replaceState({}, document.title, '/');
    try {
      const tokens = await exchangeCodeForTokens(code);
      const idPayload = decodeJwt(tokens.id_token);
      setCookie('awana-session', tokens.access_token, tokens.expires_in);
      setCookie('awana-id-token', tokens.id_token, tokens.expires_in);
      document.getElementById('userEmail').textContent = idPayload.email || '';
    } catch (e) {
      console.error('Auth failed:', e);
      // Code was invalid/expired — send user back through login
      deleteCookie('awana-session');
      deleteCookie('awana-id-token');
      window.location.href = `${cfg.cognitoDomain}/oauth2/authorize?client_id=${cfg.clientId}&response_type=code&scope=openid+email+profile&redirect_uri=${encodeURIComponent(cfg.redirectUri)}`;
      return;
    }
  } else {
    const idToken = getIdToken();
    if (idToken) {
      try {
        const payload = decodeJwt(idToken);
        document.getElementById('userEmail').textContent = payload.email || '';
      } catch (_) { /* corrupt token */ }
    }
  }

  document.getElementById('logoutBtn').addEventListener('click', logout);
})();
