// ─────────────────────────────────────────────────────────────────────────────
// SAMPLE CODE — NOT INTENDED FOR PRODUCTION USE.
// This code is provided as a reference implementation only.
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Centralised cdk-nag suppression logic for the demo project.
 *
 * All suppressions live here so each stack only needs a single call.
 * Findings fall into three buckets:
 *
 *   1. Demo-project trade-offs — things we'd fix in production (PITR, CMK,
 *      VPC for Lambda, etc.) but skip for a reference implementation.
 *   2. CDK-generated wildcards — standard grant/invoke methods produce
 *      actions like `s3:GetObject*` and resources like `bucket/*` or `fn:*`.
 *   3. Service-specific wildcards — resources whose ARN is not known at
 *      deploy time (AgentCore runtimes, foundation models, event source
 *      mappings, etc.).
 */

import { Stack } from 'aws-cdk-lib';
import { NagSuppressions, NagPackSuppression } from 'cdk-nag';

// ─── Shared reasons ───

const DEMO = 'Demo project — not required for a reference implementation';
const CDK_GRANT = 'Wildcard actions/resources generated by CDK grant methods — standard CDK behavior';
const CDK_SFN = 'CDK Step Functions LambdaInvoke grants on both fn ARN and fn ARN:* to cover qualified/unqualified invocations';
const SVC_WILDCARD = 'Resource ARN not known at deploy time — scoped to account/region where possible';
const NO_RESOURCE_LEVEL = 'API does not support resource-level permissions';

// ─── Public API ───

/** Foundation stack — permissions boundary ceiling. */
export function suppressFoundationFindings(stack: Stack) {
  suppressCommon(stack);

  NagSuppressions.addResourceSuppressionsByPath(stack,
    `/${stack.node.id}/CreatedRoleBoundary/Resource`,
    [{ id: 'AwsSolutions-IAM5', reason: 'Permissions boundary ceiling — intentional *:* allow constrained by explicit Deny statements', appliesTo: ['Action::*', 'Resource::*'] }],
  );

  // RegisterCentralAccount provider — CDK Provider grants fn:*
  NagSuppressions.addResourceSuppressionsByPath(stack,
    `/${stack.node.id}/RegisterCentralAccountProvider/framework-onEvent/ServiceRole/DefaultPolicy/Resource`,
    [{ id: 'AwsSolutions-IAM5', reason: CDK_SFN, appliesTo: ['Resource::<RegisterCentralAccountFnE5765B82.Arn>:*'] }],
  );
}

/** Ingestion stack — Cost Explorer, Resource Explorer, Step Functions. */
export function suppressIngestionFindings(stack: Stack) {
  suppressCommon(stack);

  // Cost Explorer does not support resource-level permissions
  NagSuppressions.addResourceSuppressionsByPath(stack,
    `/${stack.node.id}/BillingDimensionsFn/ServiceRole/DefaultPolicy/Resource`,
    [{ id: 'AwsSolutions-IAM5', reason: `ce:GetDimensionValues, ce:GetCostAndUsage — ${NO_RESOURCE_LEVEL}`, appliesTo: ['Resource::*'] }],
  );

  // S3 bucket/* from CDK grant methods
  const s3Bucket: NagPackSuppression = { id: 'AwsSolutions-IAM5', reason: CDK_GRANT, appliesTo: ['Resource::<ResourceInventoryBucket468FB29E.Arn>/*'] };
  NagSuppressions.addResourceSuppressionsByPath(stack, [
    `/${stack.node.id}/ResourceInventoryFn/ServiceRole/DefaultPolicy/Resource`,
    `/${stack.node.id}/ConsolidationFn/ServiceRole/DefaultPolicy/Resource`,
    `/${stack.node.id}/BillingDimensionsFn/ServiceRole/DefaultPolicy/Resource`,
  ], [s3Bucket]);

  // Step Functions grants lambda:InvokeFunction on both ARN and ARN:*
  NagSuppressions.addResourceSuppressionsByPath(stack,
    `/${stack.node.id}/IngestionStateMachine/Role/DefaultPolicy/Resource`,
    [
      { id: 'AwsSolutions-IAM5', reason: CDK_SFN, appliesTo: [
        'Resource::<ResourceInventoryFn5C11DA00.Arn>:*',
        'Resource::<BillingDimensionsFn3A4314A8.Arn>:*',
        'Resource::<ConsolidationFn7A21CDFC.Arn>:*',
        'Resource::<ContentCrawlerFunction6DBAC4DF.Arn>:*',
      ]},
      { id: 'AwsSolutions-IAM5', reason: `xray:Put* — ${NO_RESOURCE_LEVEL}`, appliesTo: ['Resource::*'] },
    ],
  );
}

/** Evaluation stack — AgentCore runtime, Bedrock models, circuit breaker. */
export function suppressEvaluationFindings(stack: Stack, runtimeName: string) {
  suppressCommon(stack);

  // cdk-nag renders unresolved CDK tokens as <AWS::AccountId> and uses the
  // literal region string. We must match these exact patterns in appliesTo.
  const acct = '<AWS::AccountId>';
  const region = stack.region;

  // ── AgentCore runtime role — S3 prompts, S3 inventory, Cost Explorer ──
  NagSuppressions.addResourceSuppressionsByPath(stack,
    `/${stack.node.id}/RuntimeRole/DefaultPolicy/Resource`,
    [
      { id: 'AwsSolutions-IAM5', reason: `ce:GetCostAndUsage — ${NO_RESOURCE_LEVEL}`, appliesTo: ['Resource::*'] },
      { id: 'AwsSolutions-IAM5', reason: CDK_GRANT, appliesTo: [
        'Resource::<ResourceInventoryBucket468FB29E.Arn>/*',
        `Resource::arn:aws:s3:::cdk-hnb659fds-assets-${acct}-${region}/*`,
      ]},
      { id: 'AwsSolutions-IAM5', reason: 'Prompts bucket scoped to config/* prefix', appliesTo: [
        'Resource::<PromptsBucketE1E1C95D.Arn>/config/*',
      ]},
    ],
  );

  // ── AgentCore base policy — logs, X-Ray, CloudWatch, Bedrock models ──
  NagSuppressions.addResourceSuppressionsByPath(stack,
    `/${stack.node.id}/AgentRuntimeBasePolicy/Resource`,
    [
      { id: 'AwsSolutions-IAM5', reason: SVC_WILDCARD, appliesTo: [
        `Resource::arn:aws:logs:${region}:${acct}:log-group:/aws/bedrock-agentcore/runtimes/*`,
        `Resource::arn:aws:logs:${region}:${acct}:log-group:/aws/bedrock-agentcore/runtimes/*:log-stream:*`,
        `Resource::arn:aws:logs:${region}:${acct}:log-group:/aws/bedrock-agentcore/runtimes/${runtimeName}*`,
        `Resource::arn:aws:bedrock-agentcore:${region}:${acct}:workload-identity-directory/default/workload-identity/${runtimeName}-*`,
        `Resource::arn:aws:bedrock:${region}::foundation-model/*`,
        `Resource::arn:aws:bedrock:${region}:${acct}:inference-profile/*`,
      ]},
      { id: 'AwsSolutions-IAM5', reason: `xray:Put*, cloudwatch:PutMetricData — ${NO_RESOURCE_LEVEL}`, appliesTo: ['Resource::*'] },
    ],
  );

  // ── Processor + Evaluation Lambdas — AgentCore invoke, circuit breaker ──
  const circuitBreaker: NagPackSuppression[] = [
    { id: 'AwsSolutions-IAM5', reason: 'Event source mapping UUID not known at deploy time — scoped to account/region', appliesTo: [
      `Resource::arn:aws:lambda:${region}:${acct}:event-source-mapping:*`,
    ]},
  ];
  NagSuppressions.addResourceSuppressionsByPath(stack,
    `/${stack.node.id}/ProcessorFunction/ServiceRole/DefaultPolicy/Resource`,
    [
      ...circuitBreaker,
      { id: 'AwsSolutions-IAM5', reason: SVC_WILDCARD, appliesTo: [`Resource::arn:aws:bedrock-agentcore:${region}:${acct}:runtime/${runtimeName}*`] },
    ],
  );
  NagSuppressions.addResourceSuppressionsByPath(stack,
    `/${stack.node.id}/EvaluationFunction/ServiceRole/DefaultPolicy/Resource`,
    [
      ...circuitBreaker,
      { id: 'AwsSolutions-IAM5', reason: SVC_WILDCARD, appliesTo: [`Resource::arn:aws:bedrock-agentcore:${region}:${acct}:runtime/${runtimeName}*`] },
      { id: 'AwsSolutions-IAM5', reason: CDK_GRANT, appliesTo: ['Resource::<ResourceInventoryBucket468FB29E.Arn>/*'] },
    ],
  );

  // ── Evaluation State Machine — Step Functions Lambda invoke ──
  NagSuppressions.addResourceSuppressionsByPath(stack,
    `/${stack.node.id}/EvaluationStateMachine/Role/DefaultPolicy/Resource`,
    [
      { id: 'AwsSolutions-IAM5', reason: CDK_SFN, appliesTo: ['Resource::<EvaluationFunctionDA169382.Arn>:*'] },
      { id: 'AwsSolutions-IAM5', reason: `xray:Put* — ${NO_RESOURCE_LEVEL}`, appliesTo: ['Resource::*'] },
    ],
  );
}

/** Frontend stack — Bedrock models, Organizations, BucketDeployment, edge Lambda. */
export function suppressFrontendFindings(stack: Stack) {
  suppressCommon(stack);

  const acct = '<AWS::AccountId>';
  const region = stack.region;

  // API Gateway WAF — not required for demo
  NagSuppressions.addStackSuppressions(stack, [
    { id: 'AwsSolutions-APIG3', reason: DEMO },
  ]);

  // Accounts function — organizations:ListAccounts/DescribeAccount on *
  NagSuppressions.addResourceSuppressionsByPath(stack,
    `/${stack.node.id}/AccountsFunction/ServiceRole/DefaultPolicy/Resource`,
    [{ id: 'AwsSolutions-IAM5', reason: `organizations:ListAccounts/DescribeAccount — ${NO_RESOURCE_LEVEL}`, appliesTo: ['Resource::*'] }],
  );

  // BucketDeployment custom resource — CDK-generated S3 wildcards
  NagSuppressions.addResourceSuppressionsByPath(stack,
    `/${stack.node.id}/Custom::CDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756C/ServiceRole/DefaultPolicy/Resource`,
    [{ id: 'AwsSolutions-IAM5', reason: CDK_GRANT, appliesTo: [
      'Resource::*',
      'Resource::<WebsiteBucket75C24D94.Arn>/*',
      `Resource::arn:aws:s3:::cdk-hnb659fds-assets-${acct}-${region}/*`,
    ]}],
  );

  // Feedback Analyst — Bedrock models, S3 inventory, S3 prompts, Memory
  NagSuppressions.addResourceSuppressionsByPath(stack,
    `/${stack.node.id}/FeedbackAnalystFunction/ServiceRole/DefaultPolicy/Resource`,
    [
      { id: 'AwsSolutions-IAM5', reason: SVC_WILDCARD, appliesTo: [
        `Resource::arn:aws:bedrock:${region}::foundation-model/*`,
        `Resource::arn:aws:bedrock:${region}:${acct}:inference-profile/*`,
      ]},
      { id: 'AwsSolutions-IAM5', reason: CDK_GRANT, appliesTo: [
        'Resource::<ResourceInventoryBucket468FB29E.Arn>/*',
        'Resource::<PromptsBucketE1E1C95D.Arn>/*',
      ]},
      { id: 'AwsSolutions-IAM5', reason: 'AgentCore Memory + DynamoDB stream reads require broad resource scope', appliesTo: ['Resource::*'] },
    ],
  );

  // The edge-lambda-stack is created by cloudfront.experimental.EdgeFunction as a
  // separate top-level stack. Suppressions must be applied from the app level
  // (see bin/app.ts) since addResourceSuppressionsByPath only works within
  // the stack it's called on.
}

// ─── Common suppressions applied to every stack ───

function suppressCommon(stack: Stack) {
  suppressDemoFindings(stack);
  suppressCdkWildcards(stack);
}

// ─── Demo-project suppressions (category 1) ───

function suppressDemoFindings(stack: Stack) {
  NagSuppressions.addStackSuppressions(stack, [
    // DynamoDB — no PITR, default encryption
    { id: 'AwsSolutions-DDB3', reason: DEMO },

    // SQS — SQS-managed encryption instead of CMK
    { id: 'AwsSolutions-SQS3', reason: DEMO },
    { id: 'AwsSolutions-SQS4', reason: DEMO },

    // SNS — using aws/sns key, not custom CMK
    { id: 'AwsSolutions-SNS2', reason: DEMO },
    { id: 'AwsSolutions-SNS3', reason: DEMO },

    // Lambda — no VPC, no reserved concurrency, no DLQ, runtime version
    { id: 'AwsSolutions-L1', reason: DEMO },

    // IAM — AWS managed policies (AWSLambdaBasicExecutionRole etc.)
    { id: 'AwsSolutions-IAM4', reason: DEMO },

    // S3 — no access logging
    { id: 'AwsSolutions-S1', reason: DEMO },

    // CloudFront — no access logging, no WAF, default TLS
    { id: 'AwsSolutions-CFR1', reason: DEMO },
    { id: 'AwsSolutions-CFR2', reason: DEMO },
    { id: 'AwsSolutions-CFR3', reason: DEMO },
    { id: 'AwsSolutions-CFR4', reason: DEMO },

    // Cognito — no MFA, no AdvancedSecurity
    { id: 'AwsSolutions-COG1', reason: DEMO },
    { id: 'AwsSolutions-COG2', reason: DEMO },
    { id: 'AwsSolutions-COG3', reason: DEMO },

    // API Gateway — no access logging, no WAF, no usage plan
    { id: 'AwsSolutions-APIG1', reason: DEMO },
    { id: 'AwsSolutions-APIG2', reason: DEMO },
    { id: 'AwsSolutions-APIG4', reason: DEMO },
    { id: 'AwsSolutions-APIG6', reason: DEMO },

    // Step Functions — no logging at ALL level, no X-Ray
    { id: 'AwsSolutions-SF1', reason: DEMO },
    { id: 'AwsSolutions-SF2', reason: DEMO },

    // CloudWatch Logs — no CMK encryption
    { id: 'AwsSolutions-CW2', reason: DEMO },
  ]);
}

// ─── CDK-generated wildcards (category 2) ───

function suppressCdkWildcards(stack: Stack) {
  NagSuppressions.addStackSuppressions(stack, [
    // CDK S3 grant methods expand to s3:GetObject*, s3:GetBucket*, s3:List*, etc.
    { id: 'AwsSolutions-IAM5', reason: CDK_GRANT, appliesTo: [
      'Action::s3:GetObject*',
      'Action::s3:GetBucket*',
      'Action::s3:List*',
      'Action::s3:Abort*',
      'Action::s3:DeleteObject*',
    ]},
  ]);
}
